id: P004502
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:27:41.407569
source_metadata:
  id: bdr:W25268
  title: གངས་ཅན་མཁས་དབང་རིམ་བྱོན་གྱི་རྣམ་ཐར་མདོར་བསྡུས།
  author: ''
  volumes:
    43316e36fc0145e9903b2ad7ee400c65:
      image_group_id: I1PD36334
      title: ''
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
    426ec7666be94365812beb84adfb80f2:
      image_group_id: I1PD36335
      title: ''
      volume_number: 2
      total_pages: 253
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
