id: P004502
initial_creation_type: ocr
source_metadata:
  id: bdr:W25268
  title: གངས་ཅན་མཁས་དབང་རིམ་བྱོན་གྱི་རྣམ་ཐར་མདོར་བསྡུས།
  author: ''
  volumes:
    43316e36fc0145e9903b2ad7ee400c65:
      image_group_id: I1PD36334
      title: ''
      volume_number: 1
      total_pages: 834
    426ec7666be94365812beb84adfb80f2:
      image_group_id: I1PD36335
      title: ''
      volume_number: 2
      total_pages: 253
